import { DEFAULT_CHARACTER_LOOK, DEFAULT_THEME } from '../data/characterCustomization'
import type { GameState } from '../data/types'
import { EVENT_COOLDOWN_MAX, EVENT_COOLDOWN_MIN } from './constants'
import { createDefaultAchievementStats } from './achievementsEngine'
import { DEFAULT_NARRATOR_LINE } from './narrator'
import { INITIAL_MONEY, INITIAL_POWER, nextLifeEventCooldownSeconds } from './balanceConfig'

function randomCooldown(): number {
  return (
    Math.floor(Math.random() * (EVENT_COOLDOWN_MAX - EVENT_COOLDOWN_MIN + 1)) + EVENT_COOLDOWN_MIN
  )
}

export function createInitialState(): GameState {
  return {
    money: INITIAL_MONEY,
    power: INITIAL_POWER,
    recruitLevels: {},
    businessLevels: {},
    territoriesOwned: {},
    playerName: '',
    age: 18,
    ageProgressPoints: 0,
    agePulseNonce: 0,
    title: 'Street Nobody',
    titlePulseNonce: 0,
    narratorLine: DEFAULT_NARRATOR_LINE,
    narratorEventKey: 'welcome',
    passiveScale: 1,
    tickCount: 0,
    lastSessionEndedAtMs: 0,
    streetLuckEndTick: 0,
    streetLuckMoneyMult: 2,
    secondsUntilEvent: randomCooldown(),
    pendingEventId: null,
    pendingMinorStreetEventId: null,
    pausedMinorStreetEventId: null,
    pendingRivalEventContext: null,
    rivalStoryEventNonce: 0,
    homeThreatPulseNonce: 0,
    dangerPulseNonce: 0,
    dangerCooldownRemaining: 0,
    shopUpgradesPurchased: {},
    achievementsUnlocked: {},
    achievementStats: createDefaultAchievementStats(),
    achievementToastQueue: [],
    heat: 0,
    heatCrackdownEndTick: 0,
    heatCrackdownNonce: 0,
    heatCapGraceEndTick: 0,
    heatGracePeriodActive: false,
    heatMaxDebuffKind: null,
    heatWarningLatch: false,
    heatWarningSfxNonce: 0,
    lastManualHustleTick: 0,
    rivals: {},
    secondsUntilRivalCheck: 20 + Math.floor(Math.random() * 25),
    rivalAttackCooldownTicks: 0,
    rivalAmbientCooldownTicks: 0,
    pendingRivalEncounter: null,
    revengeTargetId: null,
    rivalIncomeMult: 1,
    rivalWarningNonce: 0,
    rivalAttackFlashNonce: 0,
    rivalRevengeNonce: 0,
    avatarReactionNonce: 0,
    avatarReactionKind: null,
    saveVersion: 15,
    houseLevel: 0,
    relationshipUnlocked: false,
    hasPartner: false,
    partnerName: '',
    affection: 0,
    loyalty: 0,
    happiness: 0,
    married: false,
    lifePrestigeMarried: 0,
    lifePrestigeSolo: 0,
    secondsUntilLifeEvent: nextLifeEventCooldownSeconds(),
    pendingLifeEventId: null,
    pausedMinorLifeEventId: null,
    lifeEventHistory: [],
    lifeSocialCooldownTicks: 0,
    lastLifePositiveSocialTick: 0,
    lifeGriefDebuffEndTick: 0,
    playerWarHp: 100,
    playerWarMaxHp: 100,
    warIncomingBlocks: 0,
    pendingWarStrike: null,
    gangWarRivalId: null,
    gangWarTargetTerritoryId: null,
    gangWarSmallWar: false,
    gangWarAttackUses: 0,
    gangWarDefendUses: 0,
    territoryOwner: {},
    territoryFailMult: {},
    lifeEventForcedId: null,
    gangIntelRivalId: null,
    gangWarStrikePrepared: false,
    gangWarSurpriseDoublePending: false,
    houseOwnedItems: {},
    housePlacements: {},
    housePlacementNonce: 0,
    characterLook: { ...DEFAULT_CHARACTER_LOOK },
    characterTheme: DEFAULT_THEME,
    customizationNonce: 0,
    businessUnlockHighlightNonce: 0,
    businessUnlockHighlightIds: [],
    territoryFirstCaptureSeen: {},
    lifeBranchFlags: {},
    heatLaunderCooldownEndTick: 0,
    partnerGoal: null,
    eventLog: [],
    eventOutcomeBanner: null,
  }
}
